server:
  port: 8080
  address: 10.61.194.227
  
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ltq_adep?useSSL=false&serverTimezone=UTC
    username: root
    password: ltqltq2005
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl